chore(ci): retry build electron if failed (#1066)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,7 +38,7 @@ jobs:
           name: editor_playground_dist
           path: ./packages/playground/dist
 
-  build_packages:
+  build_package:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -52,10 +52,10 @@ jobs:
   build_electron:
     strategy:
       matrix:
-        electron_build_command:
-          - build:win
-          - build:mac
-          - build:linux
+        electron_build_target:
+          - win
+          - mac
+          - linux
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v3
@@ -78,9 +78,17 @@ jobs:
           tag_name: "${{ env.RINO_APP_VERSION }}"
           append_body: false
 
-      - name: Build electron
+      - name: Build dependencies
         run: |
-          pnpm turbo run ${{ matrix.electron_build_command }} --filter='electron'
+          pnpm build electron^...
+
+      - name: Build electron and upload to GitHub release if necessary
+        run: >
+          cd packages/electron;
+          ( echo "==== Attempt: 1 ====" && pnpm build:${{ matrix.electron_build_target }} ) ||
+          ( echo "==== Attempt: 2 ====" && pnpm build:${{ matrix.electron_build_target }} ) ||
+          ( echo "==== Attempt: 3 ====" && pnpm build:${{ matrix.electron_build_target }} ) ||
+          ( echo "====== Failed ======" && exit 1 )
         env:
           ELECTRON_APPLE_ID_NAME: ${{ secrets.ELECTRON_APPLE_ID_NAME }}
           ELECTRON_APPLE_ID: ${{ secrets.ELECTRON_APPLE_ID }}
@@ -88,30 +96,6 @@ jobs:
           CSC_LINK: ${{ secrets.ELECTRON_MAC_P12_BASE64 }}
           CSC_KEY_PASSWORD: ${{ secrets.ELECTRON_MAC_P12_PASSWORD }}
           GH_TOKEN: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
-
-      - name: Clean electron dist
-        run: |
-          cd packages/electron
-          echo '============== before cleaning =============='
-          find ./dist -type f
-          echo '============== cleaning ====================='
-          rm -rf ./dist/*/
-          echo '============== after cleaning ==============='
-          find ./dist -type f
-
-      - name: Upload dist (electron dmg)
-        uses: actions/upload-artifact@v3
-        if: "contains(github.event.head_commit.message, 'UPLOAD_DMG')"
-        with:
-          name: electron_dist_dmg
-          path: ./packages/electron/dist/*.dmg
-
-      - name: Upload dist (electron exe)
-        uses: actions/upload-artifact@v3
-        if: "contains(github.event.head_commit.message, 'UPLOAD_EXE')"
-        with:
-          name: electron_dist_exe
-          path: ./packages/electron/dist/*.exe
 
   test:
     runs-on: ubuntu-latest
@@ -179,8 +163,8 @@ jobs:
           vercel-args: "--meta TYPE=PREVIEW"
           working-directory: "./packages/home/dist/"
 
-      - id: step_vercel_editor
-        name: Deploy @rino.app/editor to Vercel
+      - id: step_vercel_playground
+        name: Deploy @rino.app/playground to Vercel
         continue-on-error: true
         timeout-minutes: 10
         uses: amondnet/vercel-action@v25
@@ -211,7 +195,7 @@ jobs:
             - Status: ***${{ steps.step_vercel_home.outcome }}***
             - URL: https://rino-home-${{ steps.step_branch.outputs.branch }}.ocavue.vercel.app
             ### Editor playground
-            - Status: ***${{ steps.step_vercel_editor.outcome }}***
+            - Status: ***${{ steps.step_vercel_playground.outcome }}***
             - URL: https://rino-editor-${{ steps.step_branch.outputs.branch }}.ocavue.vercel.app
 
       - name: Generate configrations for Lighthouse CI
@@ -231,6 +215,7 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - build_website
+      - build_package
       - build_electron
       - test
       - lint
@@ -292,8 +277,8 @@ jobs:
           vercel-args: "--prod --meta TYPE=PRODUCTION"
           working-directory: "./packages/home/dist/"
 
-      - id: step_vercel_editor
-        name: Deploy @rino.app/editor to Vercel
+      - id: step_vercel_playground
+        name: Deploy @rino.app/playground to Vercel
         timeout-minutes: 10
         uses: amondnet/vercel-action@v25
         with:
